version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: dependencies
          command: sudo apt-get install awscli
      - run:
          name: set assume role credential 
          command: |
            bash scripts/assume.sh
            . aws_sts_env.sh
      - run:
          name: test s3 command
          command: |
            . aws_sts_env.sh
            aws s3 ls
      - run:
          name: display CodeCommit README
          command: |
            . aws_sts_env.sh
            git config --global credential.helper '!aws --profile CircleciProfile codecommit credential-helper $@'
            git config --global credential.UseHttpPath true
            git clone https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/circleci-test
            cat circleci-test/README.md

