version: 2
jobs:
  build:
    docker:
      - image: cibuilds/aws:latest
    steps:
      - checkout
      - run:
          name: assume role credential set
          command: |
          chmod +x scripts/assume.sh
          source scripts/aws-cli-assumerole.sh
