version: 2
jobs:
  build:
    docker:
      - image: smarthr/circleci-base
    steps:
      - checkout
      - run:
          name: dependencies
          command: sudo apt-get install awscli
      - run:
          name: set assume role credential 
          command: |
            bash scripts/assume.sh
            source aws_sts_env.sh

